%    SegArray implementation of ISLOGICAL.
%    B = ISLOGICAL(A)
%    Emulates normal behavior of ISLOGICAL.
%    (see HELP ISLOGICAL for details)

% GISTIC software version 2.0
% Copyright (c) 2011-2017 Gad Getz, Rameen Beroukhim, Craig Mermel,
% Jen Dobson, Steve Schumacher, Nico Stransky, Mike Lawrence, Gordon Saksena
% All Rights Reserved.
% (See the accompanying LICENSE file for licensing details.)

function B = islogical(A)
% (code generated by unary.pl)
    try
        B = islogical(A.vals);
    catch me
        throwAsCaller(me);
    end
end
