%    SegArray implementation of ISREAL.
%    B = ISREAL(A)
%    Emulates normal behavior of ISREAL.
%    (see HELP ISREAL for details)

% GISTIC software version 2.0
% Copyright (c) 2011-2017 Gad Getz, Rameen Beroukhim, Craig Mermel,
% Jen Dobson, Steve Schumacher, Nico Stransky, Mike Lawrence, Gordon Saksena
% All Rights Reserved.
% (See the accompanying LICENSE file for licensing details.)

function B = isreal(A)
% (code generated by unary.pl)
    try
        B = isreal(A.vals);
    catch me
        throwAsCaller(me);
    end
end
