%    SegArray implementation of LOG10.
%    B = LOG10(A)
%    Emulates full array behavior of LOG10; returns a SegArray.
%    (use HELP LOG10 for details)

% GISTIC software version 2.0
% Copyright (c) 2011-2017 Gad Getz, Rameen Beroukhim, Craig Mermel,
% Jen Dobson, Steve Schumacher, Nico Stransky, Mike Lawrence, Gordon Saksena
% All Rights Reserved.
% (See the accompanying LICENSE file for licensing details.)

function B = log10(A)
% (code generated by unarray.pl)
B = A;
try
    B.vals = log10(A.vals);
catch me
    throwAsCaller(me);
end
