%    SegArray implementation of LOGICAL.
%    B = LOGICAL(A)
%    Emulates full array behavior of LOGICAL; returns a SegArray.
%    (use HELP LOGICAL for details)

% GISTIC software version 2.0
% Copyright (c) 2011-2017 Gad Getz, Rameen Beroukhim, Craig Mermel,
% Jen Dobson, Steve Schumacher, Nico Stransky, Mike Lawrence, Gordon Saksena
% All Rights Reserved.
% (See the accompanying LICENSE file for licensing details.)

function B = logical(A)
% (code generated by unarray.pl)
B = A;
try
    B.vals = logical(A.vals);
catch me
    throwAsCaller(me);
end
